# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created: Thu Sep 18 13:52:43 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(932, 800)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.scrollArea = QtGui.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 591, 715))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.verticalLayout = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.view = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.view.setText(_fromUtf8(""))
        self.view.setObjectName(_fromUtf8("view"))
        self.verticalLayout.addWidget(self.view)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 932, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.dwPrinterOptions = QtGui.QDockWidget(MainWindow)
        self.dwPrinterOptions.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.dwPrinterOptions.setObjectName(_fromUtf8("dwPrinterOptions"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.formLayout_3 = QtGui.QFormLayout(self.dockWidgetContents)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.lResolution = QtGui.QLabel(self.dockWidgetContents)
        self.lResolution.setObjectName(_fromUtf8("lResolution"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.lResolution)
        self.dsbResolution = QtGui.QDoubleSpinBox(self.dockWidgetContents)
        self.dsbResolution.setDecimals(2)
        self.dsbResolution.setSingleStep(0.1)
        self.dsbResolution.setProperty("value", 0.1)
        self.dsbResolution.setObjectName(_fromUtf8("dsbResolution"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.dsbResolution)
        self.gbDelay = QtGui.QGroupBox(self.dockWidgetContents)
        self.gbDelay.setObjectName(_fromUtf8("gbDelay"))
        self.formLayout_2 = QtGui.QFormLayout(self.gbDelay)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.lBeforeOn = QtGui.QLabel(self.gbDelay)
        self.lBeforeOn.setObjectName(_fromUtf8("lBeforeOn"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.lBeforeOn)
        self.lAfterOn = QtGui.QLabel(self.gbDelay)
        self.lAfterOn.setObjectName(_fromUtf8("lAfterOn"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.lAfterOn)
        self.dsbAfterOn = QtGui.QDoubleSpinBox(self.gbDelay)
        self.dsbAfterOn.setSingleStep(0.1)
        self.dsbAfterOn.setProperty("value", 0.5)
        self.dsbAfterOn.setObjectName(_fromUtf8("dsbAfterOn"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.dsbAfterOn)
        self.lBeforeOff = QtGui.QLabel(self.gbDelay)
        self.lBeforeOff.setObjectName(_fromUtf8("lBeforeOff"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.lBeforeOff)
        self.dsbBeforeOff = QtGui.QDoubleSpinBox(self.gbDelay)
        self.dsbBeforeOff.setSingleStep(0.1)
        self.dsbBeforeOff.setProperty("value", 0.5)
        self.dsbBeforeOff.setObjectName(_fromUtf8("dsbBeforeOff"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.dsbBeforeOff)
        self.lAfterOff = QtGui.QLabel(self.gbDelay)
        self.lAfterOff.setObjectName(_fromUtf8("lAfterOff"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.lAfterOff)
        self.dsbAfterOff = QtGui.QDoubleSpinBox(self.gbDelay)
        self.dsbAfterOff.setSingleStep(0.1)
        self.dsbAfterOff.setProperty("value", 0.5)
        self.dsbAfterOff.setObjectName(_fromUtf8("dsbAfterOff"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.dsbAfterOff)
        self.dsbBeforeOn = QtGui.QDoubleSpinBox(self.gbDelay)
        self.dsbBeforeOn.setSingleStep(0.1)
        self.dsbBeforeOn.setProperty("value", 0.5)
        self.dsbBeforeOn.setObjectName(_fromUtf8("dsbBeforeOn"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.dsbBeforeOn)
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.SpanningRole, self.gbDelay)
        self.gbPretensioning = QtGui.QGroupBox(self.dockWidgetContents)
        self.gbPretensioning.setObjectName(_fromUtf8("gbPretensioning"))
        self.formLayout = QtGui.QFormLayout(self.gbPretensioning)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.lPretensioningX = QtGui.QLabel(self.gbPretensioning)
        self.lPretensioningX.setObjectName(_fromUtf8("lPretensioningX"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.lPretensioningX)
        self.dsbPretensioningX = QtGui.QDoubleSpinBox(self.gbPretensioning)
        self.dsbPretensioningX.setMaximum(9999.0)
        self.dsbPretensioningX.setSingleStep(0.1)
        self.dsbPretensioningX.setProperty("value", 1.0)
        self.dsbPretensioningX.setObjectName(_fromUtf8("dsbPretensioningX"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.dsbPretensioningX)
        self.dsbPretensioningY = QtGui.QDoubleSpinBox(self.gbPretensioning)
        self.dsbPretensioningY.setMaximum(9999.0)
        self.dsbPretensioningY.setSingleStep(0.1)
        self.dsbPretensioningY.setProperty("value", 1.0)
        self.dsbPretensioningY.setObjectName(_fromUtf8("dsbPretensioningY"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.dsbPretensioningY)
        self.lPretensioningY = QtGui.QLabel(self.gbPretensioning)
        self.lPretensioningY.setObjectName(_fromUtf8("lPretensioningY"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.lPretensioningY)
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.SpanningRole, self.gbPretensioning)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.formLayout_3.setItem(5, QtGui.QFormLayout.SpanningRole, spacerItem)
        self.gbGcode = QtGui.QGroupBox(self.dockWidgetContents)
        self.gbGcode.setObjectName(_fromUtf8("gbGcode"))
        self.formLayout_4 = QtGui.QFormLayout(self.gbGcode)
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.lGcodeLaserOn = QtGui.QLabel(self.gbGcode)
        self.lGcodeLaserOn.setObjectName(_fromUtf8("lGcodeLaserOn"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.lGcodeLaserOn)
        self.leGcodeLaserOn = QtGui.QLineEdit(self.gbGcode)
        self.leGcodeLaserOn.setObjectName(_fromUtf8("leGcodeLaserOn"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.leGcodeLaserOn)
        self.lGcodeLaserOff = QtGui.QLabel(self.gbGcode)
        self.lGcodeLaserOff.setObjectName(_fromUtf8("lGcodeLaserOff"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.lGcodeLaserOff)
        self.leGcodeLaserOff = QtGui.QLineEdit(self.gbGcode)
        self.leGcodeLaserOff.setObjectName(_fromUtf8("leGcodeLaserOff"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.leGcodeLaserOff)
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.SpanningRole, self.gbGcode)
        self.gbConnection = QtGui.QGroupBox(self.dockWidgetContents)
        self.gbConnection.setObjectName(_fromUtf8("gbConnection"))
        self.formLayout_5 = QtGui.QFormLayout(self.gbConnection)
        self.formLayout_5.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_5.setObjectName(_fromUtf8("formLayout_5"))
        self.lPrinterPort = QtGui.QLabel(self.gbConnection)
        self.lPrinterPort.setObjectName(_fromUtf8("lPrinterPort"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.LabelRole, self.lPrinterPort)
        self.lePrinterPort = QtGui.QLineEdit(self.gbConnection)
        self.lePrinterPort.setObjectName(_fromUtf8("lePrinterPort"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.FieldRole, self.lePrinterPort)
        self.lBaudrate = QtGui.QLabel(self.gbConnection)
        self.lBaudrate.setObjectName(_fromUtf8("lBaudrate"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.LabelRole, self.lBaudrate)
        self.sbPrinterBaudrate = QtGui.QSpinBox(self.gbConnection)
        self.sbPrinterBaudrate.setMaximum(1000000)
        self.sbPrinterBaudrate.setProperty("value", 115200)
        self.sbPrinterBaudrate.setObjectName(_fromUtf8("sbPrinterBaudrate"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.FieldRole, self.sbPrinterBaudrate)
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.SpanningRole, self.gbConnection)
        self.dwPrinterOptions.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dwPrinterOptions)
        self.dwPrinterControl = QtGui.QDockWidget(MainWindow)
        self.dwPrinterControl.setObjectName(_fromUtf8("dwPrinterControl"))
        self.dockWidgetContents_2 = QtGui.QWidget()
        self.dockWidgetContents_2.setObjectName(_fromUtf8("dockWidgetContents_2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.dockWidgetContents_2)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem1, 5, 0, 1, 5)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 0, 1, 1, 4)
        self.frame = QtGui.QFrame(self.dockWidgetContents_2)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout = QtGui.QGridLayout(self.frame)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.toolButton_2 = QtGui.QToolButton(self.frame)
        self.toolButton_2.setObjectName(_fromUtf8("toolButton_2"))
        self.gridLayout.addWidget(self.toolButton_2, 2, 2, 1, 1)
        self.toolButton_3 = QtGui.QToolButton(self.frame)
        self.toolButton_3.setObjectName(_fromUtf8("toolButton_3"))
        self.gridLayout.addWidget(self.toolButton_3, 2, 0, 1, 1)
        self.toolButton_5 = QtGui.QToolButton(self.frame)
        self.toolButton_5.setObjectName(_fromUtf8("toolButton_5"))
        self.gridLayout.addWidget(self.toolButton_5, 2, 1, 1, 1)
        self.toolButton_4 = QtGui.QToolButton(self.frame)
        self.toolButton_4.setObjectName(_fromUtf8("toolButton_4"))
        self.gridLayout.addWidget(self.toolButton_4, 1, 1, 1, 1)
        self.toolButton = QtGui.QToolButton(self.frame)
        self.toolButton.setObjectName(_fromUtf8("toolButton"))
        self.gridLayout.addWidget(self.toolButton, 3, 1, 1, 1)
        self.doubleSpinBox_3 = QtGui.QDoubleSpinBox(self.frame)
        self.doubleSpinBox_3.setObjectName(_fromUtf8("doubleSpinBox_3"))
        self.gridLayout.addWidget(self.doubleSpinBox_3, 0, 0, 1, 1)
        self.doubleSpinBox_4 = QtGui.QDoubleSpinBox(self.frame)
        self.doubleSpinBox_4.setObjectName(_fromUtf8("doubleSpinBox_4"))
        self.gridLayout.addWidget(self.doubleSpinBox_4, 0, 1, 1, 1)
        self.gridLayout_3.addWidget(self.frame, 4, 0, 1, 3)
        self.tbConnect = QtGui.QToolButton(self.dockWidgetContents_2)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("resources/network-disconnect.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("resources/network-connect.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.tbConnect.setIcon(icon)
        self.tbConnect.setIconSize(QtCore.QSize(32, 32))
        self.tbConnect.setCheckable(True)
        self.tbConnect.setObjectName(_fromUtf8("tbConnect"))
        self.gridLayout_3.addWidget(self.tbConnect, 0, 0, 1, 1)
        self.dwPrinterControl.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dwPrinterControl)
        self.actionFileOpen = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("resources/document-open.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFileOpen.setIcon(icon1)
        self.actionFileOpen.setObjectName(_fromUtf8("actionFileOpen"))
        self.actionBuild = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("resources/run-build.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionBuild.setIcon(icon2)
        self.actionBuild.setObjectName(_fromUtf8("actionBuild"))
        self.menuFile.addAction(self.actionFileOpen)
        self.menubar.addAction(self.menuFile.menuAction())
        self.toolBar.addAction(self.actionFileOpen)
        self.toolBar.addAction(self.actionBuild)
        self.lResolution.setBuddy(self.dsbResolution)
        self.lBeforeOn.setBuddy(self.dsbBeforeOn)
        self.lAfterOn.setBuddy(self.dsbAfterOn)
        self.lBeforeOff.setBuddy(self.dsbBeforeOff)
        self.lAfterOff.setBuddy(self.dsbAfterOff)
        self.lPretensioningX.setBuddy(self.dsbPretensioningX)
        self.lPretensioningY.setBuddy(self.dsbPretensioningY)
        self.lGcodeLaserOn.setBuddy(self.leGcodeLaserOn)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.tbConnect, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.frame.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Img2Gcode", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.dwPrinterOptions.setWindowTitle(_translate("MainWindow", "Printer options", None))
        self.lResolution.setText(_translate("MainWindow", "Resolution:", None))
        self.gbDelay.setTitle(_translate("MainWindow", "Delays", None))
        self.lBeforeOn.setText(_translate("MainWindow", "Before laser on, s:", None))
        self.lAfterOn.setText(_translate("MainWindow", "After laser on, s:", None))
        self.lBeforeOff.setText(_translate("MainWindow", "Before laser off, s:", None))
        self.lAfterOff.setText(_translate("MainWindow", "After laser off, s:", None))
        self.gbPretensioning.setTitle(_translate("MainWindow", "Pretensioning", None))
        self.lPretensioningX.setText(_translate("MainWindow", "X, mm:", None))
        self.lPretensioningY.setText(_translate("MainWindow", "Y, mm:", None))
        self.gbGcode.setTitle(_translate("MainWindow", "GCode", None))
        self.lGcodeLaserOn.setText(_translate("MainWindow", "Laser on:", None))
        self.leGcodeLaserOn.setText(_translate("MainWindow", "M106", None))
        self.lGcodeLaserOff.setText(_translate("MainWindow", "Laser off:", None))
        self.leGcodeLaserOff.setText(_translate("MainWindow", "M107", None))
        self.gbConnection.setTitle(_translate("MainWindow", "Connection", None))
        self.lPrinterPort.setText(_translate("MainWindow", "Port:", None))
        self.lePrinterPort.setText(_translate("MainWindow", "/dev/ttyUSB0", None))
        self.lBaudrate.setText(_translate("MainWindow", "Baudrate:", None))
        self.dwPrinterControl.setWindowTitle(_translate("MainWindow", "Printer control", None))
        self.toolButton_2.setText(_translate("MainWindow", "...", None))
        self.toolButton_3.setText(_translate("MainWindow", "...", None))
        self.toolButton_5.setText(_translate("MainWindow", "...", None))
        self.toolButton_4.setText(_translate("MainWindow", "...", None))
        self.toolButton.setText(_translate("MainWindow", "...", None))
        self.tbConnect.setText(_translate("MainWindow", "...", None))
        self.actionFileOpen.setText(_translate("MainWindow", "Open", None))
        self.actionFileOpen.setShortcut(_translate("MainWindow", "Ctrl+O", None))
        self.actionBuild.setText(_translate("MainWindow", "Build", None))

